### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [StefanGerrits2/frontend-data#5]
Hi Stefan, je modules zien er allemaal erg netjes uit. Over het algemeen heb ik ook weinig inhoudelijk aan te merken op je code, echter zou je in je index.js nog wat meer kunnen fragmenteren. Je kunt variabelen als je query en url ook als module importeren om dit bestand overzichtelijk te houden. Verder zijn er wat kleine verschillen in consistentie bij het aanroepen van functions en het gebruik van spaties, zie bijvoorbeeld dit stukje:

```javascript
.attr('fill', d => {return color(d);})
.attr('y', function(d, i){return 32+28*i;})
.attr('x', 150)
.text(d => {return d;})
```

Verder ben je lekker bezig, succes deze week nog.

**Comment by StefanGerrits2** [comment]
Thanks Robert!

Ik zal je feedback meenemen in mijn proces :)
