### ISSUE TITLE
Logboek

### ISSUE THREAD

**Issue by sarkis1997** [StefanGerrits2/frontend-data#9]
Je logboek is erg summier. Je zou meer punten kunnen scoren door uit te leggen welke keuzes je hebt genomen tijdens je proces. Door telkens code, die je schrijft en keuzes op baseert, in je logboek te zetten is het proces makkelijker te volgen.

**Comment by StefanGerrits2** [comment]
Keuzes die ik maak zet ik in aparte pagina's per onderwerp. Logboek is voor mij meer een overzicht wat ik welke dag heb gedaan zodat ik hier de volgende dag mee door kan gaan.
